name: Run Scheduler

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures the repo is cloned

      - name: Install Dependencies
        run: |
          cd certificate-generator  # Move into the correct directory
          npm install

      - name: Run Scheduler Script
        run: |
          cd certificate-generator  # Move into the correct directory again
          node schedular.js  # Run your script
